name: 'checkin'

on:
  push:
    branches: 
      - master
  schedule:
    - cron: '0 16 * * *'

jobs:
  netease:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout codes'
      uses: actions/checkout@v2
    - name: 'Set python'
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: 'Install requests'
      run: python -m pip install requests
    - name: 'healthcheckin'
      run: python Function/health.py
    - name: 'gladoscheckin'
      run: python Function/glados.py